<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>iWorkHelper.BootstrapperApplication</RootNamespace>
    <AssemblyName>iWorkHelper.BootstrapperApplication</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WixToolset.BootstrapperApplicationApi" Version="7.0.0" />
  </ItemGroup>
</Project>
